# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcCalc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpcCalc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpcCalc.proto\x12\x05miner\"\x07\n\x05\x45mpty\"\x1b\n\rTransactionID\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1f\n\tChallenge\x12\x12\n\ndifficulty\x18\x01 \x01(\x05\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x05\"G\n\nSubmission\x12\x15\n\rtransactionID\x18\x01 \x01(\x05\x12\x10\n\x08\x63lientID\x18\x02 \x01(\x05\x12\x10\n\x08solution\x18\x03 \x01(\t\"\x1b\n\x0bSubmitReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"\x1f\n\x0bWinnerReply\x12\x10\n\x08\x63lientID\x18\x01 \x01(\x05\"E\n\rSolutionReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08solution\x18\x02 \x01(\t\x12\x12\n\ndifficulty\x18\x03 \x01(\x05\x32\xe3\x02\n\x08MinerAPI\x12\x36\n\x10getTransactionID\x12\x0c.miner.Empty\x1a\x14.miner.TransactionID\x12\x36\n\x0cgetChallenge\x12\x14.miner.TransactionID\x1a\x10.miner.Challenge\x12;\n\x14getTransactionStatus\x12\x14.miner.TransactionID\x1a\r.miner.Status\x12\x38\n\x0fsubmitChallenge\x12\x11.miner.Submission\x1a\x12.miner.SubmitReply\x12\x35\n\tgetWinner\x12\x14.miner.TransactionID\x1a\x12.miner.WinnerReply\x12\x39\n\x0bgetSolution\x12\x14.miner.TransactionID\x1a\x14.miner.SolutionReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcCalc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=25
  _globals['_EMPTY']._serialized_end=32
  _globals['_TRANSACTIONID']._serialized_start=34
  _globals['_TRANSACTIONID']._serialized_end=61
  _globals['_CHALLENGE']._serialized_start=63
  _globals['_CHALLENGE']._serialized_end=94
  _globals['_STATUS']._serialized_start=96
  _globals['_STATUS']._serialized_end=120
  _globals['_SUBMISSION']._serialized_start=122
  _globals['_SUBMISSION']._serialized_end=193
  _globals['_SUBMITREPLY']._serialized_start=195
  _globals['_SUBMITREPLY']._serialized_end=222
  _globals['_WINNERREPLY']._serialized_start=224
  _globals['_WINNERREPLY']._serialized_end=255
  _globals['_SOLUTIONREPLY']._serialized_start=257
  _globals['_SOLUTIONREPLY']._serialized_end=326
  _globals['_MINERAPI']._serialized_start=329
  _globals['_MINERAPI']._serialized_end=684
# @@protoc_insertion_point(module_scope)
